function draw_frame(ax, R, p, axis_len)

quiver3(ax, p(1), p(2), p(3), ...
    axis_len*R(1,1), axis_len*R(2,1), axis_len*R(3,1), ...
    'r', 'LineWidth', 2, 'MaxHeadSize', 0.8);

quiver3(ax, p(1), p(2), p(3), ...
    axis_len*R(1,2), axis_len*R(2,2), axis_len*R(3,2), ...
    'g', 'LineWidth', 2, 'MaxHeadSize', 0.8);

quiver3(ax, p(1), p(2), p(3), ...
    axis_len*R(1,3), axis_len*R(2,3), axis_len*R(3,3), ...
    'b', 'LineWidth', 2, 'MaxHeadSize', 0.8);

end