function fig = visualize_optical_pivot_frame(H_new, F_h, h, opt_tip, opt_post, frame_idx)

    if nargin < 6 || isempty(frame_idx)
        frame_idx = 1;
    end

    H_obs = H_new(:, :, frame_idx).';
    T = F_h(:, :, frame_idx);

    R = T(1:3,1:3);
    p = T(1:3,4);

    h_in_em = (R * h + p).';
    tip_in_em = R * opt_tip + p;

    pts = [H_obs; h_in_em; opt_post.'; tip_in_em.'];
    span = max(pts, [], 1) - min(pts, [], 1);
    L = max(10, 0.15 * max(span));

    fig = figure('Color', 'w', ...
        'Name', sprintf('Optical Pivot Calibration - Frame %d', frame_idx));
    ax = axes(fig);
    hold(ax, 'on');
    grid(ax, 'on');
    view(ax, 35, 22);

    draw_frame_clean(ax, [0;0;0], eye(3), L, 'EM');
    draw_frame_clean(ax, p, R, L, 'Optical Probe');

    plot3(ax, H_obs(:,1), H_obs(:,2), H_obs(:,3), ...
        'o', 'MarkerSize', 7, ...
        'MarkerFaceColor', [0.00 0.45 0.74], ...
        'MarkerEdgeColor', [0.00 0.45 0.74], ...
        'DisplayName', 'H_j');

    plot3(ax, h_in_em(:,1), h_in_em(:,2), h_in_em(:,3), ...
        '+', 'MarkerSize', 9, 'LineWidth', 1.5, ...
        'Color', [0.85 0.33 0.10], ...
        'DisplayName', 'F_H h_j');

    for i = 1:size(H_obs,1)
        plot3(ax, [h_in_em(i,1), H_obs(i,1)], ...
                  [h_in_em(i,2), H_obs(i,2)], ...
                  [h_in_em(i,3), H_obs(i,3)], ...
                  '--', 'Color', [0.5 0.5 0.5], ...
                  'HandleVisibility', 'off');
    end

    plot3(ax, opt_post(1), opt_post(2), opt_post(3), ...
        'p', 'MarkerSize', 12, ...
        'MarkerFaceColor', [0.49 0.18 0.56], ...
        'MarkerEdgeColor', [0.49 0.18 0.56], ...
        'DisplayName', 'b_{post}');

    plot3(ax, tip_in_em(1), tip_in_em(2), tip_in_em(3), ...
        'd', 'MarkerSize', 10, ...
        'MarkerFaceColor', [0.85 0.33 0.10], ...
        'MarkerEdgeColor', [0.85 0.33 0.10], ...
        'DisplayName', 'F_H b_{tip}');

    quiver3(ax, p(1), p(2), p(3), ...
        tip_in_em(1)-p(1), tip_in_em(2)-p(2), tip_in_em(3)-p(3), ...
        0, 'k', 'LineWidth', 2, 'MaxHeadSize', 0.2, ...
        'DisplayName', 'b_{tip} vector');

    xlabel(ax, 'X');
    ylabel(ax, 'Y');
    zlabel(ax, 'Z');
    title(ax, sprintf('Optical Pivot Calibration | Frame %d', frame_idx));

    set_equal_3d(ax, [H_obs; h_in_em; opt_post.'; tip_in_em.']);
    daspect(ax, [1 1 1]);
    legend(ax, 'Location', 'bestoutside');
end