function plotSimulationSnapshotsConical(log, x_s, x_t, alpha, view_option)

N = length(log.t);

snapshot_idx = round(linspace(1, N, 5));
snapshot_idx(1)   = 1;
snapshot_idx(end) = N;

set(gcf, 'Color', 'w');

vis = initConicalImpedanceVisualizer(x_s, x_t, alpha, log.p(:,1), view_option);

% remove existing legend from init
delete(findall(gcf, 'Type', 'legend'));

% remove live moving objects from init
moving_fields = {'p','pc','u','Fin','Fout','Fspring','Fdamp','Ftan'};

for i = 1:length(vis.handles)
    h = vis.handles{i};

    for j = 1:length(moving_fields)
        fname = moving_fields{j};

        if isfield(h, fname) && isgraphics(h.(fname))
            delete(h.(fname));
        end
    end
end

%% ===== Snapshot plotting =====
for i = 1:length(vis.handles)
    ax = vis.axs(i);
    hold(ax, 'on');

    % full trajectory
    plot3(ax, log.p(1,:), log.p(2,:), log.p(3,:), ...
        'b-', ...
        'LineWidth', 1.5, ...
        'HandleVisibility', 'off');

    for n = 1:length(snapshot_idx)
        k = snapshot_idx(n);

        p = log.p(:,k);
        info = log.info(k);

        % end-effector snapshot
        plot3(ax, p(1), p(2), p(3), ...
            'ro', ...
            'MarkerFaceColor', 'r', ...
            'MarkerSize', 8, ...
            'HandleVisibility', 'off');

        % closest point
        plot3(ax, info.p_c(1), info.p_c(2), info.p_c(3), ...
            'ko', ...
            'MarkerFaceColor', 'y', ...
            'MarkerSize', 6, ...
            'HandleVisibility', 'off');

        % preferred direction / cone axis direction
        quiver3(ax, ...
            info.p_c(1), info.p_c(2), info.p_c(3), ...
            vis.scale.u * info.a(1), ...
            vis.scale.u * info.a(2), ...
            vis.scale.u * info.a(3), ...
            0, ...
            'Color', 'g', ...
            'LineWidth', 2, ...
            'HandleVisibility', 'off');

        % input force
        quiver3(ax, ...
            p(1), p(2), p(3), ...
            vis.scale.force * log.F_input(1,k), ...
            vis.scale.force * log.F_input(2,k), ...
            vis.scale.force * log.F_input(3,k), ...
            0, ...
            'r', ...
            'LineWidth', 2, ...
            'HandleVisibility', 'off');

        % spring force
        quiver3(ax, ...
            p(1), p(2), p(3), ...
            vis.scale.force * info.F_spring(1), ...
            vis.scale.force * info.F_spring(2), ...
            vis.scale.force * info.F_spring(3), ...
            0, ...
            'Color', 'magenta', ...
            'LineWidth', 2, ...
            'HandleVisibility', 'off');

        % damping force
        quiver3(ax, ...
            p(1), p(2), p(3), ...
            vis.scale.force * info.F_damping(1), ...
            vis.scale.force * info.F_damping(2), ...
            vis.scale.force * info.F_damping(3), ...
            0, ...
            'Color', [1.0 0.5 0.0], ...
            'LineWidth', 2, ...
            'HandleVisibility', 'off');

        % tangent force
        quiver3(ax, ...
            p(1), p(2), p(3), ...
            vis.scale.force * info.F_tangent(1), ...
            vis.scale.force * info.F_tangent(2), ...
            vis.scale.force * info.F_tangent(3), ...
            0, ...
            'g', ...
            'LineWidth', 2, ...
            'HandleVisibility', 'off');

        % output force
        quiver3(ax, ...
            p(1), p(2), p(3), ...
            vis.scale.force * log.F(1,k), ...
            vis.scale.force * log.F(2,k), ...
            vis.scale.force * log.F(3,k), ...
            0, ...
            'b', ...
            'LineWidth', 2, ...
            'HandleVisibility', 'off');
    end

    grid(ax, 'on');
end

%% ===== Clean snapshot legend =====
if strcmpi(view_option, 'all')
    ax_all = findall(gcf, 'Type', 'axes');
    ax_leg = [];

    for i = 1:length(ax_all)
        if strcmp(get(ax_all(i), 'Visible'), 'off')
            ax_leg = ax_all(i);
            break;
        end
    end

    if isempty(ax_leg)
        ax_leg = vis.axs(1);
    end
else
    ax_leg = vis.axs(1);
end

hold(ax_leg, 'on');

legend_scale = 0.6;

h_traj = plot3(ax_leg, [0 1], [0 0], [0 0], ...
    'b-', ...
    'LineWidth', 1.5);

h_p = plot3(ax_leg, 0, 0, 0, ...
    'ro', ...
    'MarkerFaceColor', 'r', ...
    'MarkerSize', 8);

h_pc = plot3(ax_leg, 0, 0, 0, ...
    'ko', ...
    'MarkerFaceColor', 'y', ...
    'MarkerSize', 6);

h_u = quiver3(ax_leg, 0, 0, 0, legend_scale, 0, 0, 0, ...
    'Color', 'g', ...
    'LineWidth', 2);

h_Fin = quiver3(ax_leg, 0, 0, 0, legend_scale, 0, 0, 0, ...
    'r', ...
    'LineWidth', 2);

h_Fspring = quiver3(ax_leg, 0, 0, 0, legend_scale, 0, 0, 0, ...
    'Color', 'magenta', ...
    'LineWidth', 2);

h_Fdamp = quiver3(ax_leg, 0, 0, 0, legend_scale, 0, 0, 0, ...
    'Color', [1.0 0.5 0.0], ...
    'LineWidth', 2);

h_Ftan = quiver3(ax_leg, 0, 0, 0, legend_scale, 0, 0, 0, ...
    'g', ...
    'LineWidth', 2);

h_Fout = quiver3(ax_leg, 0, 0, 0, legend_scale, 0, 0, 0, ...
    'b', ...
    'LineWidth', 2);

legend(ax_leg, ...
    [h_traj, h_p, h_pc, h_u, h_Fin, h_Fspring, h_Fdamp, h_Ftan, h_Fout], ...
    {'trajectory', ...
     'end-effector snapshots', ...
     'closest point', ...
     'cone axis direction a', ...
     'F input', ...
     'F spring: kD', ...
     'F damping: -Bv', ...
     'F tangent', ...
     'F output'}, ...
    'Location', 'layout');

axis(ax_leg, [-1 1 -1 1 -1 1]);
axis(ax_leg, 'off');
set(ax_leg, 'Visible', 'off');
set(ax_leg, 'FontSize', 20);

end